"""
Basic parsing example: Extract a variable from a log message.

This example demonstrates the core log-surgeon workflow:
1. Create a Parser
2. Define patterns with named capture groups
3. Compile the parser (required before use)
4. Parse log events and access extracted data

Key concepts:
- Named capture groups: (?<name>pattern) syntax extracts and labels matched text
- PATTERN constants: Pre-built regex patterns for common log elements
- Log types: Templates generated by replacing variables with placeholders
"""

from log_surgeon import PATTERN, Parser

# Sample log line to parse
log_line = "16/05/04 04:24:58 INFO Registering worker with 1 core and 4.0 GiB ram\n"

# Step 1: Create a parser instance
parser = Parser()

# Step 2: Define extraction patterns using add_var()
#
# Pattern breakdown:
#   (?<memory_gb>...)  - Named capture group: extracts matched text as "memory_gb"
#   {PATTERN.FLOAT}    - Pre-built pattern matching decimal numbers (e.g., "4.0", "3.14")
#   GiB ram            - Literal text that must appear after the number
#
# The rf"..." syntax is a raw f-string:
#   r = raw string (no need to escape backslashes in regex)
#   f = f-string (allows {PATTERN.FLOAT} interpolation)
parser.add_var("resource", rf"(?<memory_gb>{PATTERN.FLOAT}) GiB ram")

# Step 3: Compile the parser (required before parsing)
# This builds the internal DFA for efficient matching
parser.compile()

# Step 4: Parse a single log event
event = parser.parse_event(log_line)

# Step 5: Access the extracted data
print("=== Extracted Data ===")
print(f"Message:  {event.get_log_message().strip()}")
print(f"LogType:  {event.get_log_type().strip()}")
print(f"Variables: {event}")

# Access individual fields by name
print(f"\nmemory_gb = {event['memory_gb']}")

# Expected output:
# === Extracted Data ===
# Message:  16/05/04 04:24:58 INFO Registering worker with 1 core and 4.0 GiB ram
# LogType:  16/05/04 04:24:58 INFO Registering worker with 1 core and <memory_gb> GiB ram
# Variables: {
#   "memory_gb": "4.0"
# }
#
# memory_gb = 4.0
