from typing import IO, Union

from log_event import LogEvent

class ReaderParser:
    def __init__(self, input_stream: IO[bytes], schema_content: str): ...
    def next_log_event(self) -> Union[LogEvent, None]: ...
    def reset_input_stream(input_stream: IO[bytes]) -> bool: ...
